### PR TITLE
fix: Use a proper config in renderState()

### LINKED ISSUE #698: "state_adaptive_color" option is confusing since the left "state" text is used for displaying states for all entities
The `state_adaptive_color` may be used to visually associate a displayed state with a corresponding graph:
image
```
type: custom:mini-graph-card
entities:
  - entity: sensor.cleargrass_1_temperature
    name: Temp
    show_state: true
    color: red
    state_adaptive_color: true
  - entity: sensor.cleargrass_2_co2
    name: CO2
    show_state: true
    color: green
    state_adaptive_color: true
    y_axis: secondary
show:
  name: false
  icon: false
```
If some point is selected on the 2nd graph then the left "state" text contains a value for this point:
image
This confuses since the label has a value for the 2nd entity and a color for the 1st entity.

**Suggestion:**
If some point is selected for some entity and this entity has the `state_adaptive_color: true` option, then set the text color **accordingly to this entity**.

### PR DESCRIPTION
**Pull request by ildar170975**
Fixes https://github.com/kalkih/mini-graph-card/issues/698#issuecomment-2661560913

### CODE REVIEW

**Review by akloeckner — COMMENTED** [review]
Thanks! I had thought about starting this already myself, but then delayed it, because I wasn't sure about the logics of the changes. I left some recommendations...

File: src/main.js [hunk 1]
```diff
@@ -259,12 +259,11 @@ class MiniGraphCard extends LitElement {
...
 
   renderStates() {
-    const [firstEntityConfig] = this.config.entities;
     if (this.config.show.state)
       return html`
         <div class="states flex" loc=${this.config.align_state}>
-          ${this.renderState(firstEntityConfig, 0)}
-          <div class="states--secondary">${this.config.entities.map((entityConfig, i) => i > 0 && this.renderState(entityConfig, i) || '')}</div>
+          ${this.renderState(0)}
+          <div class="states--secondary">${i => i > 0 && this.renderState(i) || ''}</div>
```
Comment (akloeckner) [inline src/main.js:266]: I think, this lost something: We should be iterating over all `this.config.entities` and only rendering the state, if `i > 0` (because we have rendered the first state already).

**Review by akloeckner — CHANGES_REQUESTED** [review]

**Review by akloeckner — APPROVED** [review]
